package ver2_lec05.exception01;

public class ThrowArithmeticExceptionMain06 {
	
	public static void main(String[] args) throws GetArithmeticException05 {
		
		throw new GetArithmeticException05("예외 발생");
		
	}

}
