package ver2_lec05.exception01;

public class ThrowExceptionMain03 {
	
	public static void main(String[] args) throws TimeoutException04 {
		
//		throw new TimeoutException04("에러를 발생시켰습니다.");
		
		throw new TimeoutException04("이것은 파일 입출력 도중 발생한 에러입니다.");
		
	}

}
